_wandb:
    value:
        cli_version: 0.23.0
        e:
            yot7pw04knty6anafb1a86tc10b5ato1:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "973837025280"
                        used: "229734604800"
                email: bzhao@hamilton.edu
                executable: /home/bzhao/Assignment3/.venv/bin/python
                git:
                    commit: 98ba432f9fe1f5b0fc5870111d31418063e0c5ad
                    remote: https://github.com/bzhao3927/assignment-3.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-9acc7df5-5214-c539-865c-a5c91e1fda2f
                host: cs-dept-llm-3
                memory:
                    total: "32747769856"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/bzhao/Assignment3/train.py
                python: CPython 3.10.12
                root: .
                startedAt: "2025-11-20T01:03:18.337404Z"
                writerId: yot7pw04knty6anafb1a86tc10b5ato1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
            "3":
                - 2
                - 7
                - 13
                - 16
                - 66
            "4": 3.10.12
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 32
dropout:
    value: 0.3
embedding_dim:
    value: 1024
hidden_dim:
    value: 1024
learning_rate:
    value: 0.001
max_epochs:
    value: 20
max_length:
    value: 1024
num_layers:
    value: 2
num_workers:
    value: 4
vocab_size:
    value: 30522
weight_decay:
    value: 1e-05
