_wandb:
    value:
        cli_version: 0.23.0
        e:
            8ennb6a9vmegbu1p7z9rey90uk9qbmwp:
                args:
                    - checkpoints/bilstm-epoch=01-val_loss=0.24-v2.ckpt
                    - --max-length
                    - "2048"
                codePath: evaluate.py
                codePathLocal: evaluate.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "973837025280"
                        used: "240559091712"
                email: bzhao@hamilton.edu
                executable: /home/bzhao/Assignment3/.venv/bin/python
                git:
                    commit: 98ba432f9fe1f5b0fc5870111d31418063e0c5ad
                    remote: https://github.com/bzhao3927/assignment-3.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-9acc7df5-5214-c539-865c-a5c91e1fda2f
                host: cs-dept-llm-3
                memory:
                    total: "32747769856"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/bzhao/Assignment3/evaluate.py
                python: CPython 3.10.12
                root: /home/bzhao/Assignment3
                startedAt: "2025-11-20T02:09:45.161077Z"
                writerId: 8ennb6a9vmegbu1p7z9rey90uk9qbmwp
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
max_length:
    value: 2048
