_wandb:
    value:
        cli_version: 0.23.0
        e:
            3z0te8yvxe2daz9weucku29wgaz102lj:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "973837025280"
                        used: "201450881024"
                email: bzhao@hamilton.edu
                executable: /home/bzhao/Assignment3/.venv/bin/python
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-9acc7df5-5214-c539-865c-a5c91e1fda2f
                host: cs-dept-llm-3
                memory:
                    total: "32747769856"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/bzhao/Assignment3/train.py
                python: CPython 3.10.12
                root: .
                startedAt: "2025-11-13T01:40:13.826150Z"
                writerId: 3z0te8yvxe2daz9weucku29wgaz102lj
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 53
                - 103
            "3":
                - 7
                - 13
                - 16
                - 66
            "4": 3.10.12
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
batch_size:
    value: 32
dropout:
    value: 0.5
embedding_dim:
    value: 128
hidden_dim:
    value: 256
learning_rate:
    value: 0.001
max_epochs:
    value: 20
max_length:
    value: 256
num_layers:
    value: 2
num_workers:
    value: 4
weight_decay:
    value: 1e-05
